### ISSUE TITLE
Set example path depending upon OS

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/linter-cookstyle#1]
Does not work by default on Windows because of path setting.

**Comment by mattstratton** [comment]
This actually might not be needed.

**Comment by Arcanemagus** [comment]
Generally the name of the executable is the default, letting the system's `$PATH`/`%PATH%` figure it out, for people with bizarre setups or broken `$PATH`s though the setting let's them fix it 😉.

**Comment by mattstratton** [comment]
Yeah, I opened this issue when a user told me it wasn't working for them, and they were on Windows (I hadn't tested on Windows yet) and somehow in my memory I recalled setting the full path as the default. I think what is better is to provide the sample Windows path in addition to the sample *nix path.

**Comment by mattstratton** [comment]
This does not seem to be an issue.
