### ISSUE TITLE
automatically install dependent packages

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/linter-cookstyle#3]
There's a race condition in that it doesn't activate the plugin unless it's in a chef file, so it won't work if language-chef isn't installed. 

Adding
```
 activate: ->
    @subscriptions = new CompositeDisposable
```

might help. See https://github.com/AtomLinter/linter-foodcritic/blob/master/lib/main.coffee

**Comment by Arcanemagus** [comment]
Actually your package is _activating_ no matter what, however Linter (or any other consumer of the `provideLinter` service) should only be calling it on files of the `source.ruby.chef` scope.

If you want `language-chef` to automatically be installed for your users:

Add `atom-package-deps` as a dependency:
```ShellScript
$ npm install --save atom-package-deps
```

Add a line like this to your `activate` method:
```coffeescript
activate: ->
  require('atom-package-deps').install('linter-cookstyle')
```

And then in your `package.json` add:
```json
{
  "package-deps": [
    "linter",
    "language-chef"
  ]
}
```

**Comment by mattstratton** [comment]
Yeah, I tried that, but it didn't seem to kick off the `atom-package-deps`, but to be honest, I didn't spend a lot of time on it yet. 

Now that I think about it, the problem was simply that when I was testing, I added `atom-package-deps` to my dependencies, but never actually installed it in the package, so my testing probably failed.

**Comment by mattstratton** [comment]
Thanks for the tip, @Arcanemagus! I was on the right track originally, but I must have missed something. It works now, and the new version has been published.
