### ISSUE TITLE
Update to linter v2

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/linter-cookstyle#7]
See https://github.com/steelbrain/linter/blob/master/docs/guides/upgrading-to-standard-linter-v2.md  and http://steelbrain.me/2017/03/13/linter-v2-released.html for more details

**Comment by Arcanemagus** [comment]
Note also if you bump `atom-package-deps` to v4.5.0 you can specify `linter:2.0.0` as a package dependency and it will ensure that as a _minimum_ version installed for you.

**Comment by mattstratton** [comment]
I am assuming I need to make sure my code is working with v2 before doing so, right? :)

**Comment by Arcanemagus** [comment]
v1 providers work just fine with linter v2, so you could do that whenever you want. That's just there so that when you _do_ update to a v2 provider, you can be sure your users have a version of Linter that works for them.

**Comment by mattstratton** [comment]
Fixed in ff0da88a04643cde2e4ebf2fbefbd17861293574

**Comment by mattstratton** [comment]
@Arcanemagus I didn't enforce the version of linter to 2.1.0 in the currently released version - I am testing it locally, and it's complaining that it cannot find it:

```
Package-Deps] Unable to install linter:2.1.0 , Error: Request for package information failed: Not Foundcomplete @ /Users/mattstratton/Dropbox/src/github.com/mattstratton/linter-cookstyle/node_modules/atom-package-deps/lib/view.js:69
```

This is how I have my package-deps set up:
```
  "package-deps": [
    "linter:2.1.0",
    "language-chef"
  ],
```
Am I missing something obvious?

**Comment by mattstratton** [comment]
disregard. Forgot to update my node_modules after bumping the version of atom-package-deps :)
